# Generated by Django 5.0.2 on 2024-03-12 11:33

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('saris_admission', '0001_initial'),
        ('saris_calendar', '0001_initial'),
        ('saris_curriculum', '0001_initial'),
        ('saris_institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'stages',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_transfer.stage')),
            ],
            options={
                'verbose_name': 'Approver',
                'verbose_name_plural': 'approvers',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transfer_type', models.CharField(choices=[('PROGRAM', 'Program'), ('CAMPUS', 'Campus')], max_length=255)),
                ('request_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255, null=True)),
                ('request_date', models.DateField(auto_now=True, null=True)),
                ('request_summary', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicsemester')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_admission.enrollment')),
                ('new_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.campus')),
                ('new_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saris_curriculum.program')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saris_transfer.stage')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'transfers',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_date', models.DateField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_transfer.stage')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saris_transfer.transfer')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'approvals',
                'ordering': ['stage'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
