"""
Django settings for saris project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

BASE_URL="http://127.0.0.1:8000/"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*_@+dt$$q#kyv(cqxotqj5*obapm&)v)qe-q%!+m8=*+^0k=0j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    '127.0.0.1',
    'sound-directly-elk.ngrok-free.app'
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1',
    'https://sound-directly-elk.ngrok-free.app'
]


# Saris applications
SARIS_APPS = [
    'oauth',
    'account',
    'saris_admission',
    'saris_assessment',
    'saris_billing',
    'saris_calendar',
    'saris_curriculum',
    'saris_grading',
    'saris_graduation',
    'saris_headship',
    'saris_institution',
    'saris_registration',
    'saris_students',
    'saris_staffportal',
    'saris_studentportal',
    'saris_transfer',
    'saris_timetable',   
]

# Application definition
INSTALLED_APPS = [
    'jazzmin', # django-jazzmin -admin theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'qr_code',

    # thirdparty
    'fontawesomefree',  # django-fontawasesome
    'active_link',  # django-activelink
    'betterforms',  # django-betterforms
    'formtools',  # django-foomtools
    'import_export',  # django-import-export
    'django_bootstrap5',  # django-bootstrap5
    'django_tables2',  # django-tables2
    'django_filters',  # django-filters
    'django_countries',  # django-countries
    'dpo',

] + SARIS_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saris.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'saris_tags': 'saris.templatetags.saris_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'saris.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'saris',
        'USER': 'root',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '3306',
    }
    
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_URL = 'static/'


# Media Folder settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication model used instead of the original django user model
AUTH_USER_MODEL = 'account.User'

# A user who is not authenticated will be redirected to this url
LOGIN_URL = 'login'
# After login, user will be redirected to this url
LOGIN_REDIRECT_URL = 'account'

# Email notification configurations
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'saris@luanar.ac.mw'
EMAIL_HOST_PASSWORD = 'mails@2022'
EMAIL_USE_TLS = True
EMAIL_USE_SSH = False

# Celery settings
CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"


# DPO Integration Settings
DPO_END_POINT = "https://secure.3gdirectpay.com/API/v6/"
DPO_PAYMENT_URL = "https://secure.3gdirectpay.com/payv2.php"
DPO_COMPANY_TOKEN = "8D3DA73D-9D7F-4E09-96D4-3D44E7A83EA3"
DPO_PAYMENT_CURRENCY = "MWK"
DPO_PAYMENT_TIME_LIMIT = 5
DPO_SERVICE_TYPE = 5525 


# Django Tables
DJANGO_TABLES2_TABLE_ATTRS = {
    'class': 'table table-striped table-borderless',
    'thead': {'class': 'table-light', },
}

# Django-Jazzmin Theme Settings
JAZZMIN_SETTINGS = {
    "site_title": "SARIS",
    "site_header": "SARIS",
    "site_brand": "SARIS",
    "site_logo": "assets/images/logo.png",
    "login_logo": "assets/images/logo.png",
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "SARIS Admin",
    "welcome_user": "SARIS",
    "copyright": "LUANAR",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "sidebar": "sidebar-light-info",
}
