# Generated by Django 5.0.2 on 2024-03-12 11:27

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saris_institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Academic Activity',
                'verbose_name_plural': 'academic activities',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'academic years',
                'ordering': ['-start_year'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.campus')),
            ],
            options={
                'verbose_name': 'Academic Semester',
                'verbose_name_plural': 'academic semesters',
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AcademicSemesterActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255)),
                ('academic_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saris_calendar.academicactivity')),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saris_calendar.academicsemester')),
            ],
            options={
                'verbose_name': 'Academic Semester Activity',
                'verbose_name_plural': 'academic semesters activities',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='activities',
            field=models.ManyToManyField(through='saris_calendar.AcademicSemesterActivity', to='saris_calendar.academicactivity'),
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicyear'),
        ),
    ]
