# Generated by Django 5.0.2 on 2024-03-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saris_admission', '0001_initial'),
        ('saris_assessment', '0001_initial'),
        ('saris_calendar', '0001_initial'),
        ('saris_curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseappeal',
            options={'ordering': ['-semester'], 'verbose_name': 'Course Appeal', 'verbose_name_plural': 'course appeals'},
        ),
        migrations.RemoveField(
            model_name='courseappeal',
            name='student_course',
        ),
        migrations.AddField(
            model_name='courseappeal',
            name='academic_semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicsemester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseappeal',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='saris_curriculum.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseappeal',
            name='course_attempt',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CARRYOVER', 'Carryover'), ('REPEAT', 'Repeat'), ('SUP', 'Sup')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseappeal',
            name='course_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('NONCORE', 'Noncore'), ('ELECTIVE', 'Elective'), ('AUDIT', 'Audit')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseappeal',
            name='enrollment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='saris_admission.enrollment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseappeal',
            name='semester',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
