# Generated by Django 5.0.2 on 2024-03-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saris_assessment', '0002_alter_courseappeal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseappeal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GRADED', 'Graded'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=255),
        ),
    ]
