# Generated by Django 5.0.2 on 2024-03-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saris_assessment', '0003_alter_courseappeal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentrule',
            old_name='failed_core',
            new_name='has_failed_core',
        ),
        migrations.RenameField(
            model_name='assessmentrule',
            old_name='failed_cov',
            new_name='has_failed_cov',
        ),
        migrations.RenameField(
            model_name='assessmentrule',
            old_name='failed_rfc',
            new_name='has_failed_resit',
        ),
        migrations.RenameField(
            model_name='assessmentrule',
            old_name='failed_sup',
            new_name='has_failed_sup',
        ),
        migrations.RenameField(
            model_name='assessmentrule',
            old_name='continuing',
            new_name='is_first_year',
        ),
        migrations.RenameField(
            model_name='assessmentrule',
            old_name='repeating',
            new_name='is_resit',
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='max_cgpa',
            field=models.FloatField(verbose_name='Maximum GPA'),
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='min_cgpa',
            field=models.FloatField(verbose_name='Minimum GPA'),
        ),
    ]
