# Generated by Django 5.0.2 on 2024-03-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saris_assessment', '0004_rename_failed_core_assessmentrule_has_failed_core_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentrule',
            old_name='has_failed_resit',
            new_name='has_failed_rfc',
        ),
        migrations.RenameField(
            model_name='assessmentrule',
            old_name='is_resit',
            new_name='is_repeating',
        ),
    ]
