# Generated by Django 5.0.2 on 2024-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saris_assessment', '0005_rename_has_failed_resit_assessmentrule_has_failed_rfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseappeal',
            name='appeal_type',
            field=models.CharField(choices=[('COURSE REMARK', 'Course Remark'), ('GRADE CORRECTION', 'Grade Correction')], max_length=255),
        ),
    ]
