# Generated by Django 5.0.2 on 2024-03-20 09:11

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saris_admission', '0001_initial'),
        ('saris_assessment', '0006_alter_courseappeal_appeal_type'),
        ('saris_calendar', '0001_initial'),
        ('saris_curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseappeal',
            old_name='new_continous_grade',
            new_name='continous_grade',
        ),
        migrations.RenameField(
            model_name='courseappeal',
            old_name='new_endsemester_grade',
            new_name='endsemester_grade',
        ),
        migrations.CreateModel(
            name='Supplementary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_type', models.CharField(choices=[('CORE', 'Core'), ('NONCORE', 'Noncore'), ('ELECTIVE', 'Elective'), ('AUDIT', 'Audit')], max_length=255)),
                ('course_attempt', models.CharField(choices=[('NORMAL', 'Normal'), ('CARRYOVER', 'Carryover'), ('REPEAT', 'Repeat'), ('SUP', 'Sup')], max_length=255)),
                ('semester', models.IntegerField()),
                ('continous_grade', models.FloatField(blank=True, null=True)),
                ('endsemester_grade', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GRADED', 'Graded')], default='PENDING', max_length=255)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicsemester')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_curriculum.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_admission.enrollment')),
            ],
            options={
                'verbose_name': 'Supplementary',
                'verbose_name_plural': 'supplementary',
                'ordering': ['-semester'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
