# Generated by Django 5.0.2 on 2024-03-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saris_assessment', '0007_rename_new_continous_grade_courseappeal_continous_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterresult',
            options={'ordering': ['created_at'], 'verbose_name': 'Semester Result', 'verbose_name_plural': 'semester results'},
        ),
    ]
