# Generated by Django 5.0.2 on 2024-03-12 11:31

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saris_admission', '0001_initial'),
        ('saris_calendar', '0001_initial'),
        ('saris_institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('semester', models.IntegerField()),
                ('type', models.CharField(choices=[('NORMAL', 'Normal'), ('REPEAT', 'Repeat'), ('SUP', 'Sup')], default='NORMAL', max_length=255)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('WITHDRAWAL', 'Withdrawal')], default='REGISTERED', max_length=255)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicsemester')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_admission.enrollment')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'registration',
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RegistrationPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('registration_installment', models.FloatField(blank=True, null=True)),
                ('examination_installment', models.FloatField(blank=True, null=True)),
                ('results_installment', models.FloatField(blank=True, null=True)),
                ('block_registration', models.BooleanField(default=True)),
                ('block_examination', models.BooleanField(default=True)),
                ('block_results', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.campus')),
            ],
            options={
                'verbose_name': 'Registration Policy',
                'verbose_name_plural': 'registration policies',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
