# Generated by Django 5.0.2 on 2024-03-12 11:30

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saris_calendar', '0001_initial'),
        ('saris_curriculum', '0001_initial'),
        ('saris_institution', '0001_initial'),
        ('saris_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('semester', models.IntegerField(default=1)),
                ('initial_semester', models.IntegerField(default=1)),
                ('intake_type', models.CharField(blank=True, choices=[('GENERIC', 'Generic'), ('MATURE', 'Mature')], max_length=255, null=True)),
                ('sponsorship_type', models.CharField(blank=True, choices=[('SELF', 'Self'), ('GRANT', 'Grant'), ('SCHOLARSHIP', 'Scholarship'), ('GOVERNMENT', 'Government')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed'), ('RESERVED', 'Reserved'), ('GRADUATED', 'Graduated'), ('WITHDRAWAL', 'Withdrawal')], default='ENROLLED', max_length=255, null=True)),
                ('is_compensated', models.BooleanField(blank=True, default=False, null=True)),
                ('is_graduating', models.BooleanField(blank=True, default=False, null=True)),
                ('is_certified', models.BooleanField(blank=True, default=False, null=True)),
                ('award_name', models.CharField(blank=True, max_length=255, null=True)),
                ('award_class', models.CharField(blank=True, max_length=255, null=True)),
                ('award_level', models.CharField(blank=True, choices=[('SHORTCOURSE', 'Shortcourse'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('BACHELORS', 'Bachelors'), ('HONOURS', 'Honours'), ('PG_CERTIFICATE', 'Pg Certificate'), ('PG_DIPLOMA', 'Pg Diploma'), ('MASTERS', 'Masters'), ('DOCTORATE', 'Doctorate')], max_length=255, null=True)),
                ('award_gpa', models.FloatField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.campus')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_curriculum.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_students.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'enrollments',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WithdrawalType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('ACADEMIC SEMESTER', 'Academic Semester'), ('ACADEMIC YEAR', 'Academic Year'), ('INDEFINATE', 'Indefinate')], max_length=255)),
            ],
            options={
                'verbose_name': 'Withdrawal type',
                'verbose_name_plural': 'withdrawal types',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('semester', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=255)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicsemester')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_admission.enrollment')),
                ('withdrawal_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_admission.withdrawaltype')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'withdrawals',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
