# Generated by Django 5.0.2 on 2024-03-12 11:32

import dirtyfields.dirtyfields
import django.db.models.deletion
import saris.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saris_admission', '0001_initial'),
        ('saris_calendar', '0001_initial'),
        ('saris_institution', '0001_initial'),
        ('saris_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.campus')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'bank accounts',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoice_number', models.CharField(default=saris.utils.reference_number, editable=False, max_length=255, unique=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invoice_date', models.DateField()),
                ('currency', models.CharField(choices=[('MWK', 'Mwk'), ('USD', 'Usd'), ('GBP', 'Gbp'), ('ZAR', 'Zar')], default='MWK', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=255)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicsemester')),
                ('enrollment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='saris_admission.enrollment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_billing.service')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('MWK', 'Mwk'), ('USD', 'Usd'), ('GBP', 'Gbp'), ('ZAR', 'Zar')], default='MWK', max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.campus')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_billing.service')),
            ],
            options={
                'verbose_name': 'Service Fee',
                'verbose_name_plural': 'service fees',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RemarkFee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('saris_billing.servicefee',),
        ),
        migrations.CreateModel(
            name='RepeatCourseFee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('saris_billing.servicefee',),
        ),
        migrations.CreateModel(
            name='SupplementaryFee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('saris_billing.servicefee',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(default=saris.utils.reference_number, max_length=255)),
                ('trans_date', models.DateField()),
                ('trans_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=255)),
                ('trans_mode', models.CharField(choices=[('CASH', 'Cash'), ('ELECTRONIC', 'Electronic'), ('BANK DEPOSIT', 'Bank Deposit'), ('AUTO CREDIT', 'Auto Credit'), ('AUTO DEBIT', 'Auto Debit')], max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('MWK', 'Mwk'), ('USD', 'Usd'), ('GBP', 'Gbp'), ('ZAR', 'Zar')], default='MWK', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_students.student')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('MWK', 'Mwk'), ('USD', 'Usd'), ('GBP', 'Gbp'), ('ZAR', 'Zar')], default='MWK', max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.campus')),
                ('intake_type', models.CharField(choices=[('GENERIC', 'Generic'), ('MATURE', 'Mature')], max_length=255)),
                ('program_level', models.CharField(choices=[('SHORTCOURSE', 'Shortcourse'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('BACHELORS', 'Bachelors'), ('HONOURS', 'Honours'), ('PG_CERTIFICATE', 'Pg Certificate'), ('PG_DIPLOMA', 'Pg Diploma'), ('MASTERS', 'Masters'), ('DOCTORATE', 'Doctorate')], max_length=255)),
                ('tuition_type', models.CharField(choices=[('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_billing.service')),
            ],
            options={
                'verbose_name': 'Tuition Fee',
                'verbose_name_plural': 'tuition fees',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
