# Generated by Django 5.0.2 on 2024-03-12 11:28

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saris_calendar', '0001_initial'),
        ('saris_institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguredCurriculum',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('semester', models.IntegerField()),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicsemester')),
            ],
            options={
                'verbose_name': 'Configured Curriculum',
                'verbose_name_plural': 'configured curriculum',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('credit_hours', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'courses',
                'ordering': ['code'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfiguredCourse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_type', models.CharField(blank=True, choices=[('CORE', 'Core'), ('NONCORE', 'Noncore'), ('ELECTIVE', 'Elective'), ('AUDIT', 'Audit')], max_length=255, null=True)),
                ('semester', models.IntegerField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saris_curriculum.configuredcurriculum')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_curriculum.course')),
            ],
            options={
                'verbose_name': 'Configured courses',
                'verbose_name_plural': 'configured courses',
                'ordering': ['course__code'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('years', models.IntegerField(default=4)),
                ('semesters', models.IntegerField(default=8)),
                ('max_semesters', models.IntegerField(blank=True, null=True)),
                ('min_credit_hours', models.FloatField(blank=True, null=True)),
                ('max_credit_hours', models.FloatField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, choices=[('UNDERGRADUATE', 'Undergraduate'), ('POSTGRADUATE', 'Postgraduate')], max_length=255, null=True)),
                ('program_level', models.CharField(blank=True, choices=[('SHORTCOURSE', 'Shortcourse'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('BACHELORS', 'Bachelors'), ('HONOURS', 'Honours'), ('PG_CERTIFICATE', 'Pg Certificate'), ('PG_DIPLOMA', 'Pg Diploma'), ('MASTERS', 'Masters'), ('DOCTORATE', 'Doctorate')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_institution.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'programs',
                'ordering': ['code'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MasterCurriculum',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_type', models.CharField(blank=True, choices=[('CORE', 'Core'), ('NONCORE', 'Noncore'), ('ELECTIVE', 'Elective'), ('AUDIT', 'Audit')], max_length=255, null=True)),
                ('semester', models.IntegerField()),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_curriculum.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_curriculum.program')),
            ],
            options={
                'verbose_name': 'Master Curriculum',
                'verbose_name_plural': 'master curriculum',
                'ordering': ['course__code'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='configuredcurriculum',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_curriculum.program'),
        ),
    ]
