OAUTH_NAME='luanar'
OAUTH_CLIENT_ID='9988802d-e43c-4a3d-9349-fb3558f88c43' # dev_client_id
OAUTH_CLIENT_SECRET='M3oYesNyF3u2KQUEnwZxQffAfha92LCJI23QNeWX' # dev_client_secret
OAUTH_TOKEN_URL='https://accounts.luanar.ac.mw/oauth/token'
OAUTH_AUTHORIZE_URL='https://accounts.luanar.ac.mw/oauth/authorize'
OAUTH_USERINFO_URL='https://accounts.luanar.ac.mw/api/user'
#OAUTH_REDIRECT_URL='http://127.0.0.1:8000/oauth/authorize'
OAUTH_REDIRECT_URL='https://sound-directly-elk.ngrok-free.app/oauth/authorize'
STATE_CODE_LENGTH = 20
