# Generated by Django 5.0.2 on 2024-03-12 11:33

import dirtyfields.dirtyfields
import django.db.models.deletion
import saris.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saris_admission', '0001_initial'),
        ('saris_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_calendar.academicyear')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'sessions',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_admission.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_graduation.session')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'candidates',
                'ordering': ['-enrollment__award_gpa'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PENDING', max_length=45)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='saris_graduation/booklet')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saris_graduation.session')),
            ],
            options={
                'verbose_name': 'Booklet',
                'verbose_name_plural': 'booklets',
            },
            bases=(saris.models.WorkMixin, dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
